# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_filter2D_f_0_1/base_filter2D_f_0_1.xci
# IP: The module: 'base_filter2D_f_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_filter2D_f_0_1/constraints/filter2D_f.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter2D_f_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_filter2D_f_0_1/constraints/filter2D_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter2D_f_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_filter2D_f_0_1/base_filter2D_f_0_1.xci
# IP: The module: 'base_filter2D_f_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_filter2D_f_0_1/constraints/filter2D_f.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter2D_f_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_filter2D_f_0_1/constraints/filter2D_f_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_filter2D_f_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
