# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6.xci
# IP: The module: 'base_timer_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6.xci
# IP: The module: 'base_timer_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_timer_6/base_timer_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_timer_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
