# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_erode_hls_0_0/base_erode_hls_0_0.xci
# IP: The module: 'base_erode_hls_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_erode_hls_0_0/constraints/erode_hls.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_erode_hls_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_erode_hls_0_0/constraints/erode_hls_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_erode_hls_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_erode_hls_0_0/base_erode_hls_0_0.xci
# IP: The module: 'base_erode_hls_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_erode_hls_0_0/constraints/erode_hls.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_erode_hls_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_erode_hls_0_0/constraints/erode_hls_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_erode_hls_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
