# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3.xci
# IP: The module: 'base_axi_dma_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3.xci
# IP: The module: 'base_axi_dma_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Home/Documents/GitHub/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_axi_dma_0_3/base_axi_dma_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_dma_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
